### ISSUE TITLE
Bad verifyToken regex pattern

### ISSUE THREAD

**Issue by xahon** [sgr-io/telegram-bot-api#2]
https://github.com/io-sgr/telegram-bot/blob/56228d1afef0817316c130b5db43bfc7837f1c71/api/src/main/java/io/sgr/telegram/bot/api/utils/TelegramUtils.java#L28
But my previously generated token has this structure `123456789:abcdefgh-aaaabbb...` so regex must contain a hyphen in the alphanum part of token

PR #3

**Comment by SgrAlpha** [comment]
Released to Maven Central: https://search.maven.org/artifact/io.sgr.telegram/telegram-bot/1.1.1/pom
